// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xijhgiathafbingqtbtw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpamhnaWF0aGFmYmluZ3F0YnR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzMxNDksImV4cCI6MjA3MjMwOTE0OX0.U-FdUFpZLghtG0ro1tFo5O-ngUA3GJz7kb5s3HNdXnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});